from __future__ import annotations

import json
import re
from typing import Any, Protocol

from openai import OpenAI

from sql_rag_agent.config import LLMConfig


class LLMProviderProtocol(Protocol):
    def analyze_question(
        self,
        *,
        question: str,
    ) -> dict[str, Any] | None: ...

    def generate_sql_candidate(
        self,
        *,
        question: str,
        question_analysis: dict[str, Any],
        schema_context: list[dict[str, Any]],
        selected_tables: list[str],
        retrieved_context: list[dict[str, Any]],
    ) -> dict[str, Any] | None: ...

    def repair_sql_candidate(
        self,
        *,
        question: str,
        question_analysis: dict[str, Any],
        schema_context: list[dict[str, Any]],
        selected_tables: list[str],
        retrieved_context: list[dict[str, Any]],
        previous_candidate: dict[str, Any],
        execution_error: str,
        retry_count: int,
    ) -> dict[str, Any] | None: ...

    def compose_answer(
        self,
        *,
        question: str,
        candidate: dict[str, Any],
        execution_result: dict[str, Any],
        selected_tables: list[str],
    ) -> str | None: ...


class OpenAICompatibleLLMProvider:
    def __init__(self, config: LLMConfig | None = None):
        self.config = config or LLMConfig.from_env()
        self.client = None
        if self.config.is_configured:
            kwargs: dict[str, Any] = {"api_key": self.config.api_key}
            if self.config.base_url:
                kwargs["base_url"] = self.config.base_url
            self.client = OpenAI(**kwargs)

    @property
    def is_available(self) -> bool:
        return self.client is not None

    def analyze_question(
        self,
        *,
        question: str,
    ) -> dict[str, Any] | None:
        if not self.client:
            return None

        prompt = _question_analysis_prompt(question)
        content = self._complete(prompt, temperature=0.0, model=self.config.strong_model)
        parsed = _parse_json_object(content)
        if not parsed:
            return None

        normalized = {
            "question_type": parsed.get("question_type"),
            "expected_answer_type": parsed.get("expected_answer_type"),
            "requires_time_filter": parsed.get("requires_time_filter"),
            "requires_join": parsed.get("requires_join"),
            "requires_metric_definition": parsed.get("requires_metric_definition"),
            "ambiguities": parsed.get("ambiguities"),
            "llm_prompt": prompt,
            "llm_raw_response": content,
        }
        if not _is_valid_question_analysis(normalized):
            return None
        return normalized

    def generate_sql_candidate(
        self,
        *,
        question: str,
        question_analysis: dict[str, Any],
        schema_context: list[dict[str, Any]],
        selected_tables: list[str],
        retrieved_context: list[dict[str, Any]],
    ) -> dict[str, Any] | None:
        if not self.client:
            return None

        prompt = _sql_prompt(question, question_analysis, schema_context, selected_tables, retrieved_context)
        content = self._complete(prompt, temperature=0.0, model=self.config.strong_model)
        parsed = _parse_json_object(content)
        if not parsed or not parsed.get("sql"):
            return None

        return {
            "candidate_id": parsed.get("candidate_id") or "candidate_1",
            "sql": parsed["sql"].strip().rstrip(";"),
            "reasoning_summary": parsed.get("reasoning_summary") or "Generated by the configured LLM.",
            "expected_result_shape": parsed.get("expected_result_shape") or [],
            "filters": parsed.get("filters") or [],
            "llm_prompt": prompt,
            "llm_raw_response": content,
        }

    def repair_sql_candidate(
        self,
        *,
        question: str,
        question_analysis: dict[str, Any],
        schema_context: list[dict[str, Any]],
        selected_tables: list[str],
        retrieved_context: list[dict[str, Any]],
        previous_candidate: dict[str, Any],
        execution_error: str,
        retry_count: int,
    ) -> dict[str, Any] | None:
        if not self.client:
            return None

        prompt = _repair_sql_prompt(
            question=question,
            question_analysis=question_analysis,
            schema_context=schema_context,
            selected_tables=selected_tables,
            retrieved_context=retrieved_context,
            previous_candidate=previous_candidate,
            execution_error=execution_error,
            retry_count=retry_count,
        )
        content = self._complete(prompt, temperature=0.0, model=self.config.strong_model)
        parsed = _parse_json_object(content)
        if not parsed or not parsed.get("sql"):
            return None

        return {
            "candidate_id": parsed.get("candidate_id") or previous_candidate.get("candidate_id") or "candidate_1",
            "sql": parsed["sql"].strip().rstrip(";"),
            "reasoning_summary": parsed.get("reasoning_summary") or "Repaired by the configured LLM after execution failure.",
            "expected_result_shape": parsed.get("expected_result_shape") or previous_candidate.get("expected_result_shape") or [],
            "filters": parsed.get("filters") or previous_candidate.get("filters") or [],
            "llm_prompt": prompt,
            "llm_raw_response": content,
        }

    def compose_answer(
        self,
        *,
        question: str,
        candidate: dict[str, Any],
        execution_result: dict[str, Any],
        selected_tables: list[str],
    ) -> str | None:
        if not self.client:
            return None

        prompt = _answer_prompt(question, candidate, execution_result, selected_tables)
        content = self._complete(prompt, temperature=0.2, model=self.config.weak_model).strip()
        return content or None

    def _complete(self, prompt: str, temperature: float, model: str) -> str:
        response = self.client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a careful PostgreSQL analytics assistant. "
                        "Return concise outputs and do not invent facts."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=temperature,
        )
        return response.choices[0].message.content or ""


def _sql_prompt(
    question: str,
    question_analysis: dict[str, Any],
    schema_context: list[dict[str, Any]],
    selected_tables: list[str],
    retrieved_context: list[dict[str, Any]],
) -> str:
    schema_summary = _schema_summary(schema_context)
    semantic_summary = _semantic_context_summary(retrieved_context)
    examples = [
        {
            "question": "How many customers refunded in 17/7/2017 - 17/8/2017?",
            "sql": (
                "SELECT COUNT(DISTINCT o.customer_id) AS customer_count "
                "FROM core.returns AS r "
                "JOIN core.order_items AS oi ON oi.order_item_id = r.order_item_id "
                "JOIN core.orders AS o ON o.order_id = oi.order_id "
                "WHERE r.return_date >= DATE '2017-07-17' "
                "AND r.return_date < DATE '2017-08-18'"
            ),
        },
        {
            "question": "What is the total amount of refunded and canceled orders in 2021, and what is the combined number?",
            "sql": (
                "WITH refunded AS ( "
                "SELECT o.order_id, SUM(r.refund_amount) AS refunded_amount "
                "FROM core.orders AS o "
                "JOIN core.order_items AS oi ON oi.order_id = o.order_id "
                "JOIN core.returns AS r ON r.order_item_id = oi.order_item_id "
                "WHERE o.order_date >= DATE '2021-01-01' "
                "AND o.order_date < DATE '2022-01-01' "
                "GROUP BY o.order_id "
                "), canceled AS ( "
                "SELECT o.order_id "
                "FROM core.orders AS o "
                "WHERE o.order_date >= DATE '2021-01-01' "
                "AND o.order_date < DATE '2022-01-01' "
                "AND o.order_status = 'cancelled' "
                ") "
                "SELECT COALESCE(SUM(COALESCE(r.refunded_amount, 0)), 0) AS total_refunded_amount, "
                "(SELECT COUNT(DISTINCT o2.order_id) "
                " FROM core.orders AS o2 "
                " WHERE o2.order_date >= DATE '2021-01-01' "
                "   AND o2.order_date < DATE '2022-01-01' "
                "   AND o2.order_status = 'cancelled') AS combined_number "
                "FROM canceled AS c "
                "LEFT JOIN refunded AS r ON r.order_id = c.order_id"
            ),
        },
    ]
    return (
        "Generate exactly one PostgreSQL read-only SQL query for the user question.\n"
        "Return one JSON object only, with keys: sql, reasoning_summary, expected_result_shape, filters.\n"
        "Rules:\n"
        "- Output a single SELECT or WITH ... SELECT statement only.\n"
        "- Never use INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, COPY, CALL, DO, or multiple statements.\n"
        "- Use only the listed selected tables and listed columns.\n"
        "- Prefer schema-qualified table names and explicit table aliases.\n"
        "- Never use SELECT *.\n"
        "- If the question is time-bounded, include an explicit WHERE predicate using DATE 'YYYY-MM-DD', CURRENT_DATE, DATE_TRUNC(...), EXTRACT(...), or INTERVAL syntax.\n"
        "- If you select any non-aggregate dimension column together with aggregate expressions, include GROUP BY for those dimension columns.\n"
        "- If the answer only needs aggregate measures, do not add unnecessary label columns.\n"
        "- Keep the SQL validator-friendly and PostgreSQL-compatible.\n\n"
        "Semantic context rules:\n"
        "- LlamaIndex context suggests business meaning, synonyms, status vocabulary, joins, and caveats.\n"
        "- PostgreSQL schema below confirms valid table and column names.\n"
        "- If a user spelling differs from database values, use the database vocabulary from semantic context.\n\n"
        f"Few-shot SQL examples: {json.dumps(examples, ensure_ascii=True)}\n\n"
        f"Question: {question}\n"
        f"Question analysis: {json.dumps(question_analysis, ensure_ascii=True)}\n"
        f"Selected tables: {json.dumps(selected_tables, ensure_ascii=True)}\n"
        f"Semantic context:\n{semantic_summary}\n"
        f"Schema:\n{schema_summary}\n"
    )


def _question_analysis_prompt(question: str) -> str:
    examples = [
        {
            "question": "Which product had the highest revenue last quarter?",
            "analysis": {
                "question_type": "ranking",
                "expected_answer_type": "ranked_list",
                "requires_time_filter": True,
                "requires_join": True,
                "requires_metric_definition": True,
                "ambiguities": ["last quarter depends on the current date"],
            },
        },
        {
            "question": "How many customers refunded in 17/7/2017 - 17/8/2017?",
            "analysis": {
                "question_type": "count",
                "expected_answer_type": "number",
                "requires_time_filter": True,
                "requires_join": True,
                "requires_metric_definition": True,
                "ambiguities": [],
            },
        },
        {
            "question": "Compare desktop versus mobile delivered revenue by month this year.",
            "analysis": {
                "question_type": "comparison",
                "expected_answer_type": "table",
                "requires_time_filter": True,
                "requires_join": True,
                "requires_metric_definition": True,
                "ambiguities": [],
            },
        },
        {
            "question": "List the average review rating by product category.",
            "analysis": {
                "question_type": "aggregate",
                "expected_answer_type": "number",
                "requires_time_filter": False,
                "requires_join": True,
                "requires_metric_definition": False,
                "ambiguities": [],
            },
        },
    ]
    return (
        "Analyze the user's analytics question and return exactly one JSON object.\n"
        "Allowed question_type values: lookup, ranking, count, aggregate, comparison, trend, filter.\n"
        "Allowed expected_answer_type values: sentence, number, ranked_list, table.\n"
        "Return keys: question_type, expected_answer_type, requires_time_filter, "
        "requires_join, requires_metric_definition, ambiguities.\n"
        "ambiguities must be a JSON array of short strings.\n"
        "Do not include markdown or extra commentary.\n\n"
        "Few-shot examples:\n"
        f"{json.dumps(examples, ensure_ascii=True, indent=2)}\n\n"
        f"Question: {question}\n"
        "JSON:"
    )


def _repair_sql_prompt(
    *,
    question: str,
    question_analysis: dict[str, Any],
    schema_context: list[dict[str, Any]],
    selected_tables: list[str],
    retrieved_context: list[dict[str, Any]],
    previous_candidate: dict[str, Any],
    execution_error: str,
    retry_count: int,
) -> str:
    schema_summary = _schema_summary(schema_context)
    semantic_summary = _semantic_context_summary(retrieved_context)
    payload = {
        "question": question,
        "question_analysis": question_analysis,
        "selected_tables": selected_tables,
        "previous_sql": previous_candidate.get("sql"),
        "previous_reasoning_summary": previous_candidate.get("reasoning_summary"),
        "execution_error": execution_error,
        "retry_count": retry_count,
    }
    return (
        "Repair the PostgreSQL query after an execution failure.\n"
        "Return one JSON object only, with keys: sql, reasoning_summary, expected_result_shape, filters.\n"
        "Keep the original analytical intent, but fix the SQL so it can execute.\n"
        "Rules:\n"
        "- Output a single read-only SELECT or WITH ... SELECT statement.\n"
        "- Do not use INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, COPY, CALL, or DO.\n"
        "- Use only the listed selected tables and listed columns.\n"
        "- Prefer schema-qualified table names and explicit aliases.\n"
        "- Use the execution error as the primary clue for what to fix.\n"
        "- If a table/column/status value seems semantically wrong, revise it to a likely valid alternative.\n\n"
        f"Repair context: {json.dumps(payload, ensure_ascii=True)}\n"
        f"Semantic context:\n{semantic_summary}\n"
        f"Schema:\n{schema_summary}\n"
    )


def _answer_prompt(
    question: str,
    candidate: dict[str, Any],
    execution_result: dict[str, Any],
    selected_tables: list[str],
) -> str:
    payload = {
        "question": question,
        "selected_tables": selected_tables,
        "sql": candidate.get("sql"),
        "reasoning_summary": candidate.get("reasoning_summary"),
        "filters": candidate.get("filters", []),
        "rows": execution_result.get("rows", []),
        "row_count": execution_result.get("row_count"),
        "error": execution_result.get("error"),
    }
    return (
        "Compose a grounded, natural-language answer from this SQL execution payload. "
        "Include the direct answer, calculation basis, tables used, filters applied, and a caveat if needed. "
        "Do not mention internal trace logs. Do not invent values outside the rows.\n\n"
        f"{json.dumps(payload, ensure_ascii=True, default=str)}"
    )


def _schema_summary(schema_context: list[dict[str, Any]]) -> str:
    lines = []
    for table in schema_context:
        columns = ", ".join(f"{col['name']} ({col['type']})" for col in table.get("columns", []))
        lines.append(f"- {table['table_name']}: {columns}")
        for fk in table.get("foreign_keys", []):
            lines.append(
                "  FK "
                f"{fk['column']} -> {fk['references_table']}.{fk['references_column']}"
            )
    return "\n".join(lines)


def _semantic_context_summary(retrieved_context: list[dict[str, Any]]) -> str:
    if not retrieved_context:
        return "- No semantic context was retrieved."
    lines = []
    for item in retrieved_context:
        content = str(item.get("content") or "").strip()
        if len(content) > 1200:
            content = content[:1200] + "...[truncated]"
        lines.append(
            "- "
            f"{item.get('type', 'context')} {item.get('name', 'unnamed')} "
            f"(score={item.get('score', 0)}, source={item.get('source', '')}): {content}"
        )
    return "\n".join(lines)


def _parse_json_object(content: str) -> dict[str, Any] | None:
    cleaned = content.strip()
    fence_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", cleaned, re.DOTALL)
    if fence_match:
        cleaned = fence_match.group(1)
    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


def _is_valid_question_analysis(payload: dict[str, Any]) -> bool:
    question_type = payload.get("question_type")
    expected_answer_type = payload.get("expected_answer_type")
    ambiguities = payload.get("ambiguities")
    if question_type not in {"lookup", "ranking", "count", "aggregate", "comparison", "trend", "filter"}:
        return False
    if expected_answer_type not in {"sentence", "number", "ranked_list", "table"}:
        return False
    for key in ("requires_time_filter", "requires_join", "requires_metric_definition"):
        if not isinstance(payload.get(key), bool):
            return False
    if not isinstance(ambiguities, list) or not all(isinstance(item, str) for item in ambiguities):
        return False
    return True
