from __future__ import annotations

import json
import re
from typing import Any, Protocol

from openai import OpenAI

from sql_rag_agent.config import LLMConfig


class LLMProviderProtocol(Protocol):
    def generate_sql_candidate(
        self,
        *,
        question: str,
        question_analysis: dict[str, Any],
        schema_context: list[dict[str, Any]],
        selected_tables: list[str],
    ) -> dict[str, Any] | None: ...

    def compose_answer(
        self,
        *,
        question: str,
        candidate: dict[str, Any],
        execution_result: dict[str, Any],
        selected_tables: list[str],
    ) -> str | None: ...


class OpenAICompatibleLLMProvider:
    def __init__(self, config: LLMConfig | None = None):
        self.config = config or LLMConfig.from_env()
        self.client = None
        if self.config.is_configured:
            kwargs: dict[str, Any] = {"api_key": self.config.api_key}
            if self.config.base_url:
                kwargs["base_url"] = self.config.base_url
            self.client = OpenAI(**kwargs)

    @property
    def is_available(self) -> bool:
        return self.client is not None

    def generate_sql_candidate(
        self,
        *,
        question: str,
        question_analysis: dict[str, Any],
        schema_context: list[dict[str, Any]],
        selected_tables: list[str],
    ) -> dict[str, Any] | None:
        if not self.client:
            return None

        prompt = _sql_prompt(question, question_analysis, schema_context, selected_tables)
        content = self._complete(prompt, temperature=0.0)
        parsed = _parse_json_object(content)
        if not parsed or not parsed.get("sql"):
            return None

        return {
            "candidate_id": parsed.get("candidate_id") or "candidate_1",
            "sql": parsed["sql"].strip().rstrip(";"),
            "reasoning_summary": parsed.get("reasoning_summary") or "Generated by the configured LLM.",
            "expected_result_shape": parsed.get("expected_result_shape") or [],
            "filters": parsed.get("filters") or [],
            "llm_prompt": prompt,
            "llm_raw_response": content,
        }

    def compose_answer(
        self,
        *,
        question: str,
        candidate: dict[str, Any],
        execution_result: dict[str, Any],
        selected_tables: list[str],
    ) -> str | None:
        if not self.client:
            return None

        prompt = _answer_prompt(question, candidate, execution_result, selected_tables)
        content = self._complete(prompt, temperature=0.2).strip()
        return content or None

    def _complete(self, prompt: str, temperature: float) -> str:
        response = self.client.chat.completions.create(
            model=self.config.model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a careful PostgreSQL analytics assistant. "
                        "Return concise outputs and do not invent facts."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=temperature,
        )
        return response.choices[0].message.content or ""


def _sql_prompt(
    question: str,
    question_analysis: dict[str, Any],
    schema_context: list[dict[str, Any]],
    selected_tables: list[str],
) -> str:
    schema_summary = _schema_summary(schema_context)
    return (
        "Generate exactly one PostgreSQL read-only SQL query for the user question.\n"
        "Return one JSON object only, with keys: sql, reasoning_summary, expected_result_shape, filters.\n"
        "Rules: use explicit table aliases, never use SELECT *, never use write statements, "
        "use only listed tables and columns, and add date filters when the question includes dates.\n\n"
        f"Question: {question}\n"
        f"Question analysis: {json.dumps(question_analysis, ensure_ascii=True)}\n"
        f"Selected tables: {json.dumps(selected_tables, ensure_ascii=True)}\n"
        f"Schema:\n{schema_summary}\n"
    )


def _answer_prompt(
    question: str,
    candidate: dict[str, Any],
    execution_result: dict[str, Any],
    selected_tables: list[str],
) -> str:
    payload = {
        "question": question,
        "selected_tables": selected_tables,
        "sql": candidate.get("sql"),
        "reasoning_summary": candidate.get("reasoning_summary"),
        "filters": candidate.get("filters", []),
        "rows": execution_result.get("rows", []),
        "row_count": execution_result.get("row_count"),
        "error": execution_result.get("error"),
    }
    return (
        "Compose a grounded, natural-language answer from this SQL execution payload. "
        "Include the direct answer, calculation basis, tables used, filters applied, and a caveat if needed. "
        "Do not mention internal trace logs. Do not invent values outside the rows.\n\n"
        f"{json.dumps(payload, ensure_ascii=True, default=str)}"
    )


def _schema_summary(schema_context: list[dict[str, Any]]) -> str:
    lines = []
    for table in schema_context:
        columns = ", ".join(f"{col['name']} ({col['type']})" for col in table.get("columns", []))
        lines.append(f"- {table['table_name']}: {columns}")
        for fk in table.get("foreign_keys", []):
            lines.append(
                "  FK "
                f"{fk['column']} -> {fk['references_table']}.{fk['references_column']}"
            )
    return "\n".join(lines)


def _parse_json_object(content: str) -> dict[str, Any] | None:
    cleaned = content.strip()
    fence_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", cleaned, re.DOTALL)
    if fence_match:
        cleaned = fence_match.group(1)
    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None
